### ISSUE TITLE
Why don't we use & symbol in scanf for strings?

### ISSUE THREAD

**Issue by anusharouthu** [rohinibarla/dev#4]
int Number;
scanf("%d", &Number);
Here we use & to store that number in some memory location.

char str[100];
scanf("%[^\n]s", str);
Why dont we use & here and where that str will store.

**Comment by Mahisagar44** [comment]
Because array name "str" itself has some address which will be the starting address of first element "str[0]" in a array.

**Comment by anusharouthu** [comment]
If we take an integer array, the starting address of the first element is "Number[0]". 
Then why "&" symbol is used in an integer array.

**Comment by Mahisagar44** [comment]
To read a strings we have an format specifier %s but for to read group of integers we don't have any format specifier so there  we read each integer by using &.

**Comment by rohinibarla** [comment]
> If we take an integer array, the starting address of the first element is "Number[0]".
> Then why "&" symbol is used in an integer array.

For char array we can use the same way as we give address of &Number[0], like this &str[0] to read a character.

To read a string you need to give address and make sure you have memory adjacent to it, to read enough number of characters. So we can give any of these as arguments to scanf to read a string.

str
&str[0]

Because both are same.
Array name gives you the address of the first element in an array.

**Comment by nandeswar** [comment]
char str[100];
scanf("%[^\n]s", str);
In this process of reading  a  string we give only starting address of str, where we can store only one character but how does the remaining character's will  be stored.

**Comment by rohinibarla** [comment]
sagar answered it correctly
